"""Bundle existing experiment evidence into a server-free static demo.

This command never downloads data, fits models, generates embeddings, or runs
evaluation. Selection uses source query IDs and topic text, never model scores.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import math
from collections import defaultdict
from pathlib import Path, PurePosixPath
from urllib.parse import quote

from persona_memory_ranker.config import DATASET, DATASET_REVISION, TOKEN_BUDGET
from persona_memory_ranker.io import digest, read_csv, read_json
from persona_memory_ranker.pipeline import METHODS, load_scored, verify_evaluation, verify_frozen


SENSITIVE_TOPICS = {
    "health", "medical", "mental health", "sexual", "sexuality", "sex",
    "religion", "politics", "trauma", "addiction", "pregnancy", "fertility",
}
SENSITIVE_TERMS = (
    "diagnos", "medication", "surgery", "sexual", "suicid", "trauma",
    "pregnan", "fertility", "abuse", "depress", "anxiety", "therap",
    "medical", "symptom", "cancer", "religio", "politic", "addiction",
)


def selection_key(query: dict) -> str:
    return hashlib.sha256(f"310:static-showcase:{query['query_id']}".encode()).hexdigest()


def suitable_query(query: dict) -> bool:
    topic = str(query.get("topic_query", "")).strip().lower()
    text = str(query["query"]).lower()
    return topic not in SENSITIVE_TOPICS and not any(term in text for term in SENSITIVE_TERMS)


def source_url(source_ref: str) -> str:
    path = PurePosixPath(source_ref)
    if path.is_absolute() or ".." in path.parts or ":" in source_ref or "\\" in source_ref:
        raise ValueError(f"Invalid public dataset source path: {source_ref!r}")
    if not source_ref.startswith("data/chat_history_") or not source_ref.endswith(".json"):
        raise ValueError(f"Unexpected history source path: {source_ref!r}")
    return f"https://huggingface.co/datasets/{DATASET}/blob/{DATASET_REVISION}/{quote(source_ref, safe='/')}"


def js_bundle(data: dict) -> str:
    value = json.dumps(data, ensure_ascii=False, separators=(",", ":"), allow_nan=False)
    # Safe both as a standalone script and if someone embeds it in HTML later.
    for character, escape in (("<", "\\u003c"), (">", "\\u003e"), ("&", "\\u0026"),
                              ("\u2028", "\\u2028"), ("\u2029", "\\u2029")):
        value = value.replace(character, escape)
    return "// Generated by scripts/build_demo.py from saved experiment artifacts.\nwindow.PMR_DATA=" + value + ";\n"


def build(root: Path, split: str, limit: int) -> dict:
    evaluation_path = root / f"reports/{split}_evaluation.json"
    metrics_path = root / f"reports/{split}_query_metrics.csv"
    query_path = root / f"data/processed/{split}_queries.jsonl"
    feature_report_path = root / f"reports/features_{split}.json"
    input_paths = [evaluation_path, metrics_path, query_path, feature_report_path,
                   root / f"data/processed/features_{split}.csv",
                   root / f"artifacts/models/{split}_predictions.csv",
                   root / "artifacts/models/logistic.json",
                   root / "artifacts/models/logistic_no_position.json",
                   root / "data/processed/memories.jsonl", root / "reports/alignment.csv"]
    before = {p.relative_to(root).as_posix(): digest(p) for p in input_paths}
    evaluation = verify_evaluation(root, split)
    if split == "benchmark":
        verify_frozen(root)
    feature_report = read_json(feature_report_path)
    if evaluation.get("split") != split:
        raise ValueError("Evaluation report split does not match requested demo split")
    if feature_report["source_query_sha256"] != digest(query_path):
        raise ValueError("Feature report references different queries; finish the experiment before building")
    rows, queries, parity = load_scored(root, split)
    query_ids = {q["query_id"] for q in queries}
    if len(query_ids) != len(queries) or evaluation["queries"] != len(queries):
        raise ValueError("Evaluation query count differs from current query artifacts")
    metrics = read_csv(metrics_path)
    expected_keys = {(qid, method) for qid in query_ids for method in METHODS}
    metric_keys = {(m["query_id"], m["method"]) for m in metrics}
    if metric_keys != expected_keys or len(metrics) != len(expected_keys):
        raise ValueError("Saved per-query metrics do not cover this exact experiment")
    by_query = defaultdict(list)
    for row in rows:
        if row["query_id"] not in query_ids:
            raise ValueError("Candidate references an unknown query")
        by_query[row["query_id"]].append(row)
    selected_queries = sorted((q for q in queries if suitable_query(q)), key=selection_key)[:limit]
    if not selected_queries:
        raise ValueError("No eligible non-sensitive showcase queries; do not silently change selection rules")
    needed = {r["memory_id"] for q in selected_queries for r in by_query[q["query_id"]]}
    memories = {}
    with (root / "data/processed/memories.jsonl").open(encoding="utf-8") as handle:
        for line in handle:
            memory = json.loads(line)
            if memory["memory_id"] not in needed:
                continue
            if memory["memory_id"] in memories:
                raise ValueError("Duplicate memory identifier in source units")
            messages = memory["messages"]
            if not messages or any(not isinstance(m.get("content"), str) or not isinstance(m.get("role"), str)
                                   for m in messages):
                raise ValueError("Original role/content messages are missing")
            if "apersona" in json.dumps(memory, ensure_ascii=False).lower():
                raise ValueError("Apersona text is outside this public showcase's scope")
            memories[memory["memory_id"]] = {
                "memory_id": memory["memory_id"], "text": memory["text"],
                "turn_index": memory["turn_index"], "source_ref": memory["source_ref"],
                "source_url": source_url(memory["source_ref"]), "messages": messages,
            }
    if set(memories) != needed:
        raise ValueError("Some candidate memories have no original source unit")
    cases = []
    for query in selected_queries:
        candidates = []
        for row in by_query[query["query_id"]]:
            count = float(row["token_count"])
            if not math.isfinite(count) or count < 1 or count != int(count):
                raise ValueError("Invalid memory token count")
            candidates.append({"memory_id": row["memory_id"], "token_count": int(count),
                               **{method: float(row[method]) for method in METHODS}})
        if not candidates:
            raise ValueError("Selected query has no saved candidates")
        cases.append({"query_id": query["query_id"], "persona_id": query["persona_id"],
                      "query": query["query"], "topic_query": query.get("topic_query", ""),
                      "updated": str(query.get("updated", "false")).lower() in ("true", "1"),
                      "gold_memory_ids": query["gold_memory_ids"], "candidates": candidates})
    subset = evaluation.get("persona_limit_per_split")
    alignment_rows = [r for r in read_csv(root / "reports/alignment.csv") if r["split"] == split]
    aligned_count = sum(r["status"] == "aligned" for r in alignment_rows)
    if aligned_count != evaluation["queries"]:
        raise ValueError("Alignment coverage differs from evaluated population")
    label = "DEVELOPMENT / VALIDATION" if split == "val" else "HELD-OUT BENCHMARK"
    if subset is not None:
        label += f" / {subset}-PERSONA SUBSET PER SPLIT"
    data = {"schema_version": 1, "split": split, "split_label": label,
            "dataset": DATASET, "dataset_revision": DATASET_REVISION,
            "dataset_url": f"https://huggingface.co/datasets/{DATASET}/tree/{DATASET_REVISION}",
            "license": "CC BY 4.0", "license_url": "https://creativecommons.org/licenses/by/4.0/",
            "synthetic": True, "evaluation_queries": evaluation["queries"],
            "alignment": {"cleaned_queries": len(alignment_rows), "aligned_queries": aligned_count,
                          "excluded_queries": len(alignment_rows)-aligned_count},
            "persona_limit_per_split": subset, "reported_budget": TOKEN_BUDGET,
            "selection": "SHA-256 of seed 310 and source query ID; topic/content exclusions applied before ranking; no score-based selection",
            "showcase_queries": len(cases), "methods": METHODS, "cases": cases,
            "memories": memories, "summary": evaluation["summary"],
            "r_python_max_error": parity, "source_sha256": before}
    after = {p.relative_to(root).as_posix(): digest(p) for p in input_paths}
    if before != after:
        raise ValueError("Input artifacts changed during bundling; rebuild after the pipeline finishes")
    destination = root / "web/demo-data.js"
    destination.parent.mkdir(parents=True, exist_ok=True)
    temporary = destination.with_suffix(".js.tmp")
    temporary.write_text(js_bundle(data), encoding="utf-8")
    temporary.replace(destination)
    return {"output": str(destination), "split": split, "marker": label,
            "queries": len(cases), "memories": len(memories),
            "candidate_pairs": sum(len(q["candidates"]) for q in cases),
            "bytes": destination.stat().st_size}


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1],
                        help="Project root containing completed artifacts and web/ (defaults to this repository)")
    parser.add_argument("--split", choices=("val", "benchmark"), default="benchmark")
    parser.add_argument("--limit", type=int, default=24, help="Maximum number of deterministic showcase queries")
    args = parser.parse_args()
    if not 1 <= args.limit <= 100:
        parser.error("--limit must be between 1 and 100")
    print(json.dumps(build(args.root.resolve(), args.split, args.limit), indent=2))


if __name__ == "__main__":
    main()
