"""Build slide content and narration from actual reports, for the editable decks."""
from pathlib import Path
import argparse
import json
from collections import Counter

from persona_memory_ranker.io import read_json, read_csv, write_json
from persona_memory_ranker.pipeline import verify_evaluation, verify_frozen

ROOT = Path(__file__).resolve().parents[1]
SOURCE = "https://huggingface.co/datasets/bowen-upenn/PersonaMem-v2"


def slide(title, body, notes, chart=None):
    result = {"title": title, "body": body, "notes": notes, "source": SOURCE}
    if chart:
        result["chart"] = chart
    return result


def content(milestone):
    a = read_json(ROOT/"reports/alignment.json")
    clean = read_json(ROOT/"reports/cleaning.json")
    split = read_json(ROOT/"reports/split_audit.json")
    rows = read_csv(ROOT/"reports/alignment.csv")
    counts = Counter(r["split"] for r in rows if r["status"] == "aligned")
    population = f"{a['aligned_queries']:,} aligned queries / {a['input_queries']:,} cleaned queries"
    common = [
        slide("Persona Memory Ranker", ["Learning to retrieve relevant memories for AI personas", f"DSCI310 · {milestone} · Wenyu Chiou", "Synthetic conversations · R models · Source evidence"],
              "This project studies a practical part of personalized artificial intelligence: choosing which memories belong in the context for the next answer. A system may store a long conversation history and still retrieve the wrong evidence. The goal here is to compare several retrieval methods under the same constraints, then expose the results through a reusable interface. The course methods include logistic regression, tree ensembles, grouped cross validation, and exploratory data analysis in R. The data are synthetic conversations from PersonaMem version two. The claims in this presentation concern retrieval of annotated evidence. They do not establish psychological validity or benefit for real users."),
        slide("Research question", ["Can classical ML retrieve better supporting evidence?", "Same candidate pool; same 2,000-token context budget", "Trace every selected memory to its original messages"],
              "The research question is whether classical machine learning improves the selection of annotated evidence compared with lexical search, vector search, and a hybrid of both. A fair comparison requires holding the candidate pool and context budget constant. Otherwise a method could look stronger simply because it sees more material or returns a longer prompt. Each result keeps a memory identifier and a source reference. This allows us to inspect why the method selected a passage and whether that passage supports the query. The application is a memory engine for a persona agent, but the experiment evaluates retrieval directly. Response generation and personality inference are separate questions."),
        slide("Public dataset and observed counts", ["PersonaMem-v2 · text-only 32k histories · CC BY 4.0", "Pinned release: ed956dea41521fc4499acbc63f966e0fd3c053ba", "Observed CSV counts differ from the dataset card"],
              "The source is a publicly available dataset with a Creative Commons attribution license. We fix a particular release so that another person can reproduce the same input bytes. The dataset contains generated personas, histories, queries, and annotated conversation snippets. Downloading the actual files revealed a discrepancy: the training CSV has eighteen thousand five hundred forty-nine questions, validation has two thousand sixty-one, and the benchmark has five thousand. These observed counts differ from the rounded descriptions in the dataset card. We therefore use computed manifests and reports for the analysis, rather than treating the card as a substitute for inspecting the data. The generated nature of every example remains an important limitation.",
              {"categories": ["Train CSV", "Validation CSV", "Benchmark CSV"], "series": [{"name": "Questions", "values": [18549,2061,5000]}]}),
        slide("Persona overlap in the released splits", ["735 validation personas also occur in training", "Persona 78 overlaps development and benchmark", "Repair: preserve benchmark; regroup development by persona"],
              "The most consequential quality finding is overlap between the released partitions. All seven hundred thirty-five validation personas also appear in training. In addition, persona seventy-eight appears in the development data and in the benchmark. Splitting individual questions would therefore expose the model to the same people in training and validation. The repair preserves the two hundred benchmark personas. Their development rows are excluded. We then pool the remaining development rows and divide the seven hundred ninety-nine personas with a fixed hash and an eighty-twenty rule. This yields six hundred thirty-nine training personas and one hundred sixty validation personas. Original source row identifiers are retained for traceability."),
        slide("Cleaning with preserved source text", [f"{a['excluded_system_messages']:,} profile-bearing system messages excluded", "Original role, content and message indices retained", "One role-only assistant record recorded as missing", "Exact R/Python Unicode round trips tested"],
              "The histories themselves also need inspection. Their initial system messages contain expanded synthetic profiles. Those profiles were generation context; indexing them would give the retrieval system privileged information. We exclude system messages while retaining original source indices. One assistant record contains only a role and no content. It is recorded as a missing message, rather than being filled with invented text. Another practical issue was Unicode handling between Python and R on Windows. We corrected the process locale and tested accented text, Chinese characters, emoji, quotes, and multiline fields. These checks matter because even an invisible text conversion can prevent exact evidence alignment or alter the source that appears in the demo."),
        slide("Evidence alignment and exclusions", [population, "Gold role/content sequence must match exactly once", "Missing and ambiguous evidence receives an explicit reason"],
              f"The annotation names a supporting conversation snippet. We locate that snippet in the original history by matching the complete role and content sequence. The match must be unique. We do not repair a missing snippet with fuzzy matching or let a language model invent the location. In this run, {a['aligned_queries']} queries aligned out of {a['input_queries']} cleaned queries. The remaining {a['excluded_queries']} queries are listed in the alignment report. This exclusion changes the population on which retrieval metrics are computed, so the rate must accompany the result. A high score on the aligned subset cannot be described as performance on every original question. Inspecting the excluded cases is part of the data-quality analysis.",
              {"categories": ["Aligned", "Excluded"], "series": [{"name": "Queries", "values": [a['aligned_queries'],a['excluded_queries']]}]}),
        slide("Memory units and source references", ["One user turn plus its following assistant response", "Long turns use overlapping encoding windows", "Retrieved output retains the complete original unit", "Source roles remain visible"],
              "The retrieval unit begins with a user turn and includes its following assistant response. This is a simple and reproducible segmentation rule. It does not use the gold annotation to decide where a unit starts. Long units are encoded through overlapping windows because the selected MiniLM encoder otherwise truncates long inputs. Similarity uses the strongest window match, while the returned evidence retains the complete original unit. Role labels remain visible. In particular, an assistant statement is not automatically evidence about the user's true preference. The memory identifier and original message indices make the unit traceable. Segmentation choices can influence results and should be revisited in a separately versioned experiment."),
        slide("Exploratory analysis", [f"Aligned train: {counts['train']:,} · validation: {counts['val']:,} · benchmark: {counts['benchmark']:,}", "Inspect lengths, positions, update metadata and exclusions", "Conversation order supplies position; filenames do not supply event time"],
              "Exploratory analysis describes both the retained and excluded populations. The R notebook reports the number of queries by partition, history and memory sizes, evidence positions, query topics, and preference-update labels. Position deserves special care. The history provides message order, but it does not provide an event timestamp for every conversation. A date embedded in a generated filename is not evidence of when a user's preference was valid. We therefore use relative conversational position as a feature and describe it that way. Topic and update labels help stratify the evaluation, but they are not given to the ranker as oracle features. The notebook connects these descriptive checks to the later modeling decisions.",
              {"categories": ["Train", "Validation", "Benchmark"], "series": [{"name": "Aligned questions", "values": [counts['train'],counts['val'],counts['benchmark']]}]}),
        slide("Grouped evaluation design", ["Five-fold cross-validation holds out whole personas", "Standardization uses training data within each fold", "Validation selects a portable method before benchmark scoring", "Unannotated evidence is not necessarily irrelevant"],
              "Model development keeps personas separated at every stage. Five-fold cross validation holds out whole personas, and each fold computes its normalization values using only its training rows. The final model uses training-only normalization as well. Validation selects the portable default before the benchmark is scored. The code records a frozen protocol containing data, model, and source hashes, which helps detect accidental changes after selection. Labels need a careful interpretation: a candidate without an annotated supporting snippet is unannotated, not proven useless. We therefore describe the supervised task as prediction of benchmark evidence labels. A separate human review is needed to assess alignment and possible missing support."),
        slide("M1 findings and next steps", ["Data cleaning exposed leakage risks before modeling", "Reproducible R notebook and source-indexed memories", "100-case human audit queue requires reviewer entries", "Next: model comparison, fixed-budget evaluation and demo"],
              "The first milestone delivers a reproducible preprocessing and exploratory analysis workflow. Its main finding is that the released files require stronger checks than their descriptive documentation suggests. The overlap repair and removal of profile-bearing system messages protect the experimental comparison. The alignment report makes excluded observations visible. A one-hundred-case audit queue has been designed for a human to check source alignment and possible omitted evidence. An automatically created queue does not count as a completed human review. The next stage compares the models under a fixed budget and presents the resulting evidence selections in an interactive explorer. The final research value comes from reproducible measurements, including a negative result if learned ranking does not improve the baseline.")
    ]
    if milestone == "M1":
        return common
    results = verify_evaluation(ROOT, "benchmark")
    frozen = verify_frozen(ROOT)
    method_names = ["bm25","semantic","rrf","logistic","logistic_no_position","random_forest"]
    metrics = {(r['method'], r['metric']): r for r in results['summary']}
    selected = frozen['selected_portable_method']
    logistic_budget = metrics[('logistic', 'budget_recall')]['mean']
    vector_budget = metrics[('semantic', 'budget_recall')]['mean']
    position_difference = logistic_budget - metrics[('logistic_no_position', 'budget_recall')]['mean']
    vector_difference = logistic_budget - vector_budget
    model = read_json(ROOT/"artifacts/models/logistic.json")
    position_coefficient = dict(zip(model['feature_names'], model['coefficients']))['position']
    position_effect = "reduces" if position_coefficient < 0 else "increases" if position_coefficient > 0 else "does not change"
    paired = read_json(ROOT/"reports/paired_comparisons.json")['benchmark']
    if paired['source_metrics_sha256'] != results['output_sha256']['reports/benchmark_query_metrics.csv']:
        raise ValueError("Paired comparisons do not match the benchmark metrics")
    position_interval = next(r for r in paired['summary'] if
        r['method'] == 'logistic minus logistic_no_position' and r['metric'] == 'budget_recall')
    position_ci = f"{100*position_interval['ci_low']:+.2f} to {100*position_interval['ci_high']:+.2f}"
    position_conclusion = "The interval includes zero, so a stable contribution from position is not established." if position_interval['ci_low'] <= 0 <= position_interval['ci_high'] else "The interval excludes zero within this synthetic sample."
    updates = {(r['updated'], r['method']): float(r['mean']) for r in
               read_csv(ROOT/"reports/benchmark_updates.csv") if r['metric'] == 'budget_recall'}
    benchmark_rows = read_csv(ROOT/"reports/benchmark_query_metrics.csv")
    first_stage_misses = sum(r['method'] == 'rrf' and float(r['candidate_recall']) == 0 for r in benchmark_rows)
    method_labels = ["BM25", "Vector", "Hybrid", "Logistic", "No position", "Forest"]
    score_text = "; ".join(f"{method_labels[i]} {metrics[(m,'budget_recall')]['mean']:.1%}" for i,m in enumerate(method_names))
    added = [
        slide("Candidate generation and models", ["Union of lexical top50 and semantic top50", "BM25, vector and hybrid retrieval baselines", "R logistic regression and 300-tree random forest", "Ablation removes conversational position"],
              "All methods rank the same union of lexical and semantic candidates. The lexical method uses BM25, the semantic method uses a frozen sentence encoder, and the hybrid uses reciprocal rank fusion. The course models are logistic regression and a random forest with three hundred trees. The predictor set contains lexical relevance, semantic similarity, word overlap, memory length, and relative conversational position. We also fit a logistic model without position to examine how much the apparent benefit depends on recency information. The encoder is a fixed feature extractor, not a model trained for this assignment. This distinction keeps the contribution of the course methods visible and the experiment computationally feasible on a CPU."),
        slide("Fixed-budget retrieval", ["Whole memory units; source headers included in token cost", "Oversized units are skipped, with no evidence truncation", "Recall@5 and MRR@10 complement budget recall", "Candidate recall reveals the first-stage ceiling"],
              "A ranking is useful only if the evidence fits into the available context. The experiment therefore packs complete memory units in score order until the fixed two-thousand-token budget is exhausted. Source headers count toward the cost. A unit that does not fit is skipped, and its text is not shortened just to force a successful hit. Budget recall measures how much annotated evidence survives this process. Recall at five and reciprocal rank at ten provide complementary views of ranking quality. Candidate recall measures whether the supporting units were retrieved at all. Every recall denominator includes all annotated units for a query, including those absent from the candidate pool, so first-stage failures cannot disappear from the evaluation."),
        slide("Benchmark evidence recall", [f"{results['queries']:,} aligned questions · fixed 2,000-token budget", f"Logistic {logistic_budget:.1%} vs vector {vector_budget:.1%} · {100*vector_difference:+.2f} percentage points", "95% persona intervals and paired comparisons in RESULTS.md"],
              f"The benchmark comparison now uses the frozen methods and the isolated benchmark personas. It includes {results['queries']} aligned questions. Budget recall is the main practical comparison because the application must operate within a context limit. The observed mean results are: {score_text}. These are measurements from the generated report, not illustrative numbers. Confidence intervals are computed by resampling entire personas one thousand times. This keeps repeated questions from the same persona together during uncertainty estimation. The intervals describe variation in this synthetic sample. They do not account for every possible deployment shift, and they should not be interpreted as evidence that a method understands human psychology.",
              {"categories": method_labels, "series": [{"name": "Budget recall (%)", "values": [round(metrics[(m,'budget_recall')]['mean']*100,2) for m in method_names]}]}),
        slide("Ranking performance and position", ["Recall@5 across the same candidate pool", f"Position difference: {100*position_difference:+.2f} pp · paired 95% CI [{position_ci}]", "Order association does not establish psychological causality"],
              f"Recall at five shows whether supporting evidence appears near the top of the ranked list before budget packing. Comparing this measure with budget recall helps separate relevance from length effects. A model may rank a long correct unit highly but still fail to include it under the budget. The position ablation tests whether conversational order contributes useful information beyond lexical and semantic relevance. The full logistic model differs from the no-position model by {100*position_difference:.2f} percentage points of budget recall, with a paired ninety-five percent interval from {position_ci} percentage points. {position_conclusion} The fitted position coefficient is {position_coefficient:.3f}: later source order {position_effect} the score when the other features are held fixed. This does not establish a universal rule about which memories an agent should keep.",
              {"categories": method_labels, "series": [{"name": "Recall@5 (%)", "values": [round(metrics[(m,'recall_at_5')]['mean']*100,2) for m in method_names]}]}),
        slide("Where the ranker still fails", [f"Update-labelled: logistic {updates[('true','logistic')]:.2%} · vector {updates[('true','semantic')]:.2%}", f"Other questions: logistic {updates[('false','logistic')]:.2%} · vector {updates[('false','semantic')]:.2%}", f"{first_stage_misses:,}/{results['queries']:,} questions have no annotated candidate", "Descriptive strata; the frozen default stays unchanged"],
              f"The average result hides important differences between query groups. On questions carrying the dataset's update annotation, logistic budget recall is {updates[('true','logistic')]:.2%}, compared with {updates[('true','semantic')]:.2%} for vector retrieval. On other questions, the corresponding results are {updates[('false','logistic')]:.2%} and {updates[('false','semantic')]:.2%}. Thus the learned ranker does not outperform vector search in every group. These are descriptive subgroup results, and the update label is not an inference-time feature. We do not change the default or introduce a benchmark-tuned routing rule. Another limit occurs before ranking: {first_stage_misses} questions have no annotated supporting memory in the candidate pool. A reranker cannot recover evidence that was never retrieved. These failures identify separate targets for a future experiment."),
        slide("Interactive evidence explorer", ["Select a held-out query and compare six rankings", "Inspect original evidence and annotated support", "Change the context budget and inspect excluded units", "Static replay; local CLI handles new inputs"],
              "The interactive explorer makes the experiment inspectable. A visitor selects a query, changes the ranking method, and sees which memories fit into the chosen context budget. The table distinguishes annotated supporting evidence from unannotated candidates. Clicking a memory opens the original role-labelled messages and a source reference. The provenance graph connects the question, selected memory units, and their history source. It is a visualization of evidence flow, not a psychological model. The public page replays saved experiment cases without running a language model in the browser. A separate local command-line interface accepts a new query and a permitted memory collection, computes features, and returns a source-preserving context block."),
        slide("Reusable memory-engine interface", [f"Portable default selected on validation: {selected}", "R exports normalization parameters and logistic coefficients", f"R/Python score agreement: {results['r_python_max_error']:.2g} maximum difference", "Host retains consent, validity and mandatory-evidence rules"],
              f"The portable default selected on validation is {selected}. The Python interface also supports the exported logistic scorer. R writes the feature order, training means, scales, coefficients, and intercept into a versioned JSON artifact. Python applies the same transformation. The maximum observed discrepancy on benchmark scores is {results['r_python_max_error']:.3g}, which is below the specified numerical tolerance. This interface belongs inside a larger memory system, after the host has decided which memories are permitted and currently valid. The scorer does not grant consent, resolve contradictions, or promote inferred memory records to accepted facts. The host also checks its own language model tokenizer before assembling the final prompt, because this benchmark uses a fixed WordPiece budget."),
        slide("Conclusions and remaining limits", [f"Logistic vs vector: {100*vector_difference:+.2f} percentage points at 2,000 tokens", "Release audits exposed split and profile leakage", "Synthetic data, incomplete labels and alignment exclusions remain", "Human audit and real-domain transfer require further evidence"],
              f"The completed system provides a reproducible path from public raw conversations to R models, retrieval metrics, and a reusable evidence interface. The frozen logistic model differs from vector retrieval by {100*vector_difference:.2f} percentage points of benchmark budget recall. That is a measured retrieval result, not a downstream answer-quality result. The release audit also matters: persona overlap and profile-bearing system prompts could otherwise produce misleading results. The data are synthetic, annotations may omit useful memories, and exact alignment excludes a portion of the questions. The human audit queue still requires actual reviewer decisions. Integrating the scorer into a real memory engine requires a separate domain-transfer check. The practical outcome is a tested module and an evaluation framework that can support that next experiment without rebuilding the course project.")
    ]
    return common[:8] + added


if __name__ == "__main__":
    parser=argparse.ArgumentParser();parser.add_argument("--milestone",choices=["M1","M2"],required=True);args=parser.parse_args()
    slides=content(args.milestone)
    write_json(ROOT/f"artifacts/presentations/{args.milestone}-content.json", {"milestone":args.milestone,"duration_seconds":600 if args.milestone=='M1' else 900,"slides":slides})
    notes="\n\n".join(f"## {i}. {s['title']}\n\n{s['notes']}" for i,s in enumerate(slides,1))
    (ROOT/f"deliverables/{args.milestone}-speaker-notes.md").write_text(f"# {args.milestone} narration draft\n\nSynthetic narration is a presentation aid; review the content before course use.\n\n"+notes,encoding='utf-8')
    print(json.dumps({"milestone":args.milestone,"slides":len(slides),"narration_words":sum(len(s['notes'].split()) for s in slides)}))
