"""Evidence-linked course decks, with explicit pending human results."""
import json
import csv
from pathlib import Path
root=Path(__file__).resolve().parents[1]
source='https://huggingface.co/datasets/wenkai-li/big5_chat'
slides=[]
def add(title,body,notes,ref=source,seconds=50):
    slides.append(dict(title=title,body=body,notes=notes,source=ref,seconds=seconds))
add('Persona Memory Selector',['Behavioral examples for consistent AI role-playing','DSCI310 · Wenyu Chiou'],
'''Imagine an AI playing a careful, dependable colleague. A client suddenly asks for an earlier deadline. A personality instruction tells the AI what this colleague is like, but it does not show how that colleague might respond under pressure. Our project asks whether selecting suitable behavioral examples helps. We compare four ways to give the same AI information. The course contribution is data cleaning, classification, and a controlled comparison. A separate human evaluation will determine whether the answers actually fit the role. Classification accuracy alone cannot answer that question.''')
add('The deadline example',['Situation: a client asks for an earlier deadline','Persona: careful and dependable','Evidence: how someone handled a similar trade-off'],
'''The key decision is how to respond to the request. The character could accept immediately, ask which requirements can change, or explain why the original commitment matters. Several responses may be reasonable. We want to know whether the selected examples help the AI make a choice that fits the target character and the current situation. Simply retrieving the word deadline is not enough. Equally, adding a very polite example does not necessarily improve the decision. This example explains why we score behavioral choices and speaking style separately.''')
add('What the dataset labels mean',['100,000 synthetic dialogue records','Five Big Five dimensions, each with high and low settings','Labels describe generation settings, not diagnosed people'],
'''BIG5-CHAT provides existing labels, so we do not need to invent a large annotation project before we can train a classifier. Each record has a conversation input and a target response generated under one specified personality setting. There are ten target labels in total. A label tells us what the generation process requested. It does not guarantee that every response successfully expresses the trait. It also does not measure the other four traits. Our model predicts these dataset targets, and we keep that interpretation separate from claims about real human personality.''')
add('One record, two different speakers',['Context: what the other person says','Response: the target speaker’s behavior','Source row: the original evidence'],
'''Before training anything, we need to identify the target speaker correctly. The context may describe one person helping another person, and a field may describe how the helper feels. That feeling cannot automatically become a personality label for the person who responds. Our cleaned table therefore keeps context, target response, speaker names, and original source reference separately. We replace names with role markers for model input, while preserving the original wording for inspection. This lets a reviewer trace a prediction back to the actual data rather than a rewritten explanation.''')
add('Cleaning results',['99,656 records retained','344 records excluded with recorded reasons','Missing input and missing response counts overlap'],
'''The raw file contains one hundred thousand records. Our cleaning procedure retains ninety-nine thousand six hundred and fifty-six. We exclude three hundred and forty-four records that lack required information. The original audit found two hundred and ninety-four missing inputs and sixty-five missing responses. These counts overlap, so adding them would give the wrong exclusion total. We keep a row-level exclusion report and never ask a language model to invent the missing text. The original file is checked against a fixed hash, which makes the source bytes reproducible.''',ref='reports/selector/cleaning.json')
add('Keeping related scenarios together',['Same scenario and its variants stay in one group','Training: 69,783 · Validation: 15,296 · Test: 14,577','Test questions are also separate from their example bank'],
'''A random split by row would be misleading. The same original scenario appears under different personality settings. If one version went into training and another into testing, the model could recognize the scenario rather than generalize. We connect records sharing an original identifier, event description, or equivalent input. Whole connected groups move together. Training data fit the model. Validation data choose between approaches. Test data remain reserved until the method is fixed. Within validation and test, we also separate questions from the examples available to retrieval, so the system cannot retrieve the answer’s own scenario.''',ref='reports/selector/cleaning.json',seconds=60)
add('How text becomes model input',['TF-IDF represents distinctive words','Fixed MiniLM embeddings represent semantic similarity','Compare response alone with context plus response'],
'''A statistical classifier needs numbers rather than raw paragraphs. TF-IDF creates one representation based on how distinctive each word is in the training collection. A fixed sentence encoder gives us another representation based on learned similarities between texts. We do not train that language model in this course project. We compare whether the response alone is enough or whether including the preceding context helps classification. Long text is encoded in windows instead of silently cutting off the end. Vocabulary and fitted transformations are learned only from the training portion of each comparison.''')
add('Classifiers trained in R',['Multinomial logistic regression','Random forest','Grouped cross-validation and Macro-F1'],
'''We train two methods from the course. Multinomial logistic regression combines the numeric features to score the ten labels. Random forest combines decisions from many trees and gives a second comparison. Cross-validation means repeatedly holding out groups during training to check how well the settings transfer. We use Macro-F1, which gives each label equal weight instead of letting an easy or common label dominate. The best offline classifier and the lightweight model exported to Python are reported separately. A random forest advantage does not disappear just because logistic regression is easier to reuse.''')
add('Four controlled comparisons',['A  Fixed persona prompt','B  Vector retrieval','C  Classification-aware flat ranking','D  Classification and graph ranking'],
'''Every group uses the same target persona prompt and the same question. Group A receives no examples. Group B retrieves examples based on similarity. Group C also considers the classifier’s score for the requested trait. Group D uses a graph connecting examples with situation clusters and trait scores. The three retrieval methods start from the same fifty candidates and share the same evidence budget. Comparing C with B estimates the value of classification. Comparing D with C tests the graph’s additional value. Comparing B with A asks the more basic question of whether adding examples helps at all.''',seconds=60)
add('The graph and the prompt',['Situation groups connect related examples','Trait scores provide another retrieval signal','Examples remain distinct from personal memories'],
'''The graph is a structure for finding examples. It is not a map of psychological causes. A situation group connects related conversation contexts, and a trait connection stores a classifier score. The selected source text becomes an evidence block next to the fixed persona instruction. The prompt explicitly says these are examples, not events the AI personally experienced. That rule keeps the experiment honest: public dialogue examples can guide a response, but they cannot silently become the character’s biography.''')
add('Measuring the answers',['Two reviewers rate the same 100 blinded groups','Behavior, voice and relevance receive separate scores','Fabricated history, factual errors and invalid answers are flagged'],
'''The final evaluation asks two people to rate answers without seeing which method produced them. There are sixty primary-model personality situations, twenty situations for a second local model, and twenty factual or calculation controls. Each group contains four answers in random order. We score decisions and voice separately and record whether an answer invents personal history. The controls check whether personality examples interfere with ordinary useful answers. Both reviewers first discuss separate practice questions. Their real ratings remain blank until they complete the task. We cannot replace those ratings with the classifier’s own opinion.''',seconds=60)
add('What this project can establish',['A reusable, auditable selection component','Classification results and persona effects reported separately','Human response ratings remain pending'],
'''The useful outcome is a component that can be inspected and reused, together with evidence about when it helps. It may turn out that classification helps but the graph adds little. In that case the simpler flat selector is the supported result. A wide uncertainty interval means we need more evidence, not that the graph has been disproved. This study uses synthetic dialogues and two local models. It cannot establish human psychological validity or universal transfer to all personalities. The current delivery includes the software and evaluation materials; any claim about better persona behavior must wait for the human ratings.''',seconds=50)
m1=list(slides)
add('Why scenario context matters',['CAPS motivates conditional behavior','A stable persona can act differently in different situations','Graph edges express retrieval relationships'],
'''The cognitive-affective personality system theory is useful as a design motivation. It describes stable patterns in how a person responds to different kinds of situations. The relevant idea is not that a careful person always uses the same sentence. The pattern may change depending on uncertainty, obligations, or another person’s needs. That motivates retrieving examples matched to the current situation. Our experiment does not test the psychological theory itself. It tests whether a simple computational design inspired by context-dependent behavior improves the output of a role-playing AI.''',ref='https://pubmed.ncbi.nlm.nih.gov/7740090/',seconds=60)
add('Evidence from earlier research',['BIG5-CHAT supplies labeled examples','PersonalityEvd connects traits with supporting dialogue','ThinkPersona already studies persona graphs'],
'''Earlier research gives us both useful tools and limits on our novelty claim. BIG5-CHAT supplies the labels for our classifier. PersonalityEvd shows why a personality judgment should be linked to supporting dialogue and why momentary states differ from a longer-term trait. ThinkPersona already combines persona graphs with role-playing. We therefore do not claim to invent personality graphs. Our narrower contribution is to test the incremental value of a lightweight classifier and a graph in a controlled application component. The code and evaluation can be useful even if a simpler method wins.''',ref='https://github.com/Hualeez/ThinkPersona',seconds=60)
add('Transfer and uncertainty',['New scenario groups','A second local language model','Paired differences with scenario-level confidence intervals'],
'''Generalization is a claim we must define carefully. Holding out scenario groups checks whether the classifier and selector can handle contexts outside the training groups. A second language model checks whether the direction of the result survives one change of generator. It is a small transfer test, not proof about all models. For answer evaluation, the independent unit is the situation. Four answers from one situation and two ratings of one answer are related observations. We average reviewers within each condition and bootstrap paired situation differences. Main-model, transfer, and factual-control results are reported separately.''',seconds=60)
add('Reusable input and output',['Input: question, target trait and available examples','Output: selected text, scores and original sources','Keep the flat method if graph value is unsupported'],
'''The reusable interface receives a question, a target trait, and the examples available in the experiment. It returns selected original text with classification scores, retrieval scores, and source references. This makes each choice inspectable: we can see which source was selected and why. Structural equation modeling remains a possible later research direction with suitable measurements. For this course, the controlled comparisons provide a clearer test. The next required evidence comes from the two reviewers, who can use the prepared anonymous rating files.''',seconds=60)
slides[5]['image']='deliverables/selector/figures/data-workflow.png'
slides[9]['image']='deliverables/selector/figures/answer-workflow.png'
slides[2]['title']='Ten labels from five traits'
slides[2]['body']=['Openness · Conscientiousness · Extraversion',
                  'Agreeableness · Neuroticism',
                  'Each trait has a high and low generation setting',
                  '100,000 synthetic records · Labels describe generation settings']
slides[3]['body']=[
    'Context: “Why don’t we plan a fun outing for the kids this weekend?”',
    'Target response: “Maybe we should just stick to what we’re doing and not take any chances.”',
    'Generation label: openness_low · Training record big5-000005']
slides[3]['notes']='''Here is a real training record. One speaker proposes an outing for the children. The target speaker prefers the familiar routine and worries about a mess or bad weather. Its generation label is low openness. Notice that the worries could also suggest another trait. This is why we call these generation targets, not verified psychological truths. The two speakers have different names in the source. For the model, we replace those names with role markers, while keeping the original text and record identifier. That prevents a name from becoming an easy shortcut and keeps the prediction auditable.'''
slides[4]['chart']={'categories':['Training','Validation','Test'],'series':[{'name':'Retained records','values':[69783,15296,14577]}]}
selection_file=root/'artifacts/selector/selection.json'
names={'context_glmnet':'Context LR','context_rf':'Context RF','response_glmnet':'Response LR','response_rf':'Response RF','tfidf_glmnet':'TF-IDF LR'}
if selection_file.exists():
    selection=json.loads(selection_file.read_text(encoding='utf-8'))
    values=selection['candidates'];order=[k for k in names if k in values]
    slides[7]['title']='Classifying generation labels'
    slides[7]['body']=['Validation Macro-F1 (%) · Ten classes, unseen scenario groups',
        'Offline winner: '+names[selection['chosen_model']]+' · Portable model: '+names[selection['deployed_model']]]
    slides[7]['chart']={'categories':[names[k] for k in order],
                      'series':[{'name':'Validation Macro-F1 (%)','values':[round(values[k]*100,1) for k in order]}]}
    slides[7]['source']='artifacts/selector/selection.json'
    slides[7]['notes']=f'''These are measured validation results, not human personality ratings. Logistic regression using the response alone reaches {values['response_glmnet']*100:.1f} percent Macro-F1. Adding the context to the fixed embedding reaches {values['context_glmnet']*100:.1f} percent. So, with this representation and these data, more text did not improve classification. That does not make context useless: our retrieval step still uses it to find similar situations. The word-based TF-IDF baseline reaches {values['tfidf_glmnet']*100:.1f} percent, very close to the best score. We select the highest validation score, but do not claim that this small margin proves statistical superiority. Random forest is a course comparator with a limited parameter grid. These results show why a simple baseline and a response-only comparison are necessary before choosing a more complex design.'''
m2=[dict(slides[i]) for i in [0,1,12,13,2,3,4,5,6,7,8,9,10,14,15,11]]
m2[0]['body']=m2[0]['body']+['Automated results; human evaluation pending']
test_file=root/'artifacts/selector/test_metrics.csv'
if test_file.exists():
    with test_file.open(encoding='utf-8-sig',newline='') as f: test_rows=list(csv.DictReader(f))
    test_values={r['candidate']:float(r['macro_f1']) for r in test_rows}
    order=[k for k in names if k in test_values]
    m2[9]['title']='Classifying unseen situations'
    m2[9]['body']=['Frozen test Macro-F1 (%) · Model selection used validation only',
                  'Classification performance and human persona quality are separate outcomes']
    m2[9]['chart']={'categories':[names[k] for k in order],
                  'series':[{'name':'Test Macro-F1 (%)','values':[round(test_values[k]*100,1) for k in order]}]}
    m2[9]['source']='artifacts/selector/test_metrics.csv'
    m2[9]['notes']=f'''This chart compares all five classifiers on final test groups, after model selection was fixed. The response-only logistic model scores {test_values['response_glmnet']*100:.1f} percent Macro-F1; the TF-IDF baseline scores {test_values['tfidf_glmnet']*100:.1f} percent. Context-plus-response logistic regression scores {test_values['context_glmnet']*100:.1f} percent. Macro-F1 gives each of the ten generation targets equal weight. The separate class tables show which labels are confused, and confidence tables compare scores with observed accuracy. These measurements answer the classification question. They do not show that the AI makes more role-consistent decisions. That application claim depends on the two reviewers and the controlled answer comparison. We keep the validation-selected model regardless of this chart, and do not treat small score differences as proof of superiority.'''
for name,items in [('M1',m1),('M2',m2)]:
    items=[dict(s,seconds=s['seconds']-(10 if i<3 else 0)) for i,s in enumerate(items)]
    # M2 includes an additional minute for the live validation-demo walkthrough.
    if name=='M2': items=[dict(s,seconds=s['seconds']+int(i<6)*10) for i,s in enumerate(items)]
    out=root/f'artifacts/selector/presentations/{name}-content.json';out.parent.mkdir(parents=True,exist_ok=True)
    out.write_text(json.dumps({'slides':items,'planned_seconds':sum(s['seconds'] for s in items)},indent=2),encoding='utf-8')
    script='\n\n'.join(f"## {i+1}. {s['title']} ({s['seconds']} seconds planned)\n\n{s['notes']}\n\nSource: {s['source']}" for i,s in enumerate(items))
    target=root/f'deliverables/selector/{name}-speaker-notes.md';target.parent.mkdir(parents=True,exist_ok=True)
    target.write_text(f'# {name} spoken script\n\nTiming is a planning estimate, not a measured rehearsal. Human ratings remain pending.\n\n'+script,encoding='utf-8')
    print(name,len(items),sum(s['seconds'] for s in items))
