#!/usr/bin/env Rscript
script <- sub("^--file=", "", grep("^--file=", commandArgs(FALSE), value = TRUE)[[1]])
source(file.path(dirname(script), "common.R"))
source(file.path(dirname(script), "models.R"))
pmr_use_library(pmr_root())
pmr_main(function() {
  args <- pmr_args(c("features", "models", "output"))
  pmr_require("ranger")
  features <- pmr_validate_candidates(pmr_read_csv(args$features), labels_required = FALSE)
  path <- file.path(args$models, "models.rds")
  if (!file.exists(path)) stop("Frozen models not found: ", path, call. = FALSE)
  predictions <- pmr_predict_models(readRDS(path), features)
  pmr_write_csv(predictions, args$output)
  cat("Wrote", nrow(predictions), "frozen-model predictions to", args$output, "\n")
})
