"use strict";
const assert = require("node:assert/strict");
const {ranked, pack, evaluateCase} = require("./ranking.js");
const row = (memory_id, score, token_count) => ({memory_id, bm25: score, semantic: score,
  rrf: score, logistic: score, logistic_no_position: score, random_forest: score, token_count});
const candidates = [row("p1:t003", 0.8, 200), row("p1:t001", 0.9, 900), row("p1:t002", 0.8, 450), row("p1:t004", 0.7, 100)];
const inputOrder = candidates.map(r => r.memory_id);
const ordered = ranked(candidates, "logistic");
assert.deepEqual(ordered.map(r => r.memory_id), ["p1:t001", "p1:t002", "p1:t003", "p1:t004"]);
assert.deepEqual(candidates.map(r => r.memory_id), inputOrder, "Ranking must not mutate the stored candidate pool");
assert.deepEqual(pack(ordered, 700).map(r => r.memory_id), ["p1:t002", "p1:t003"], "Skip oversized units and pack subsequent complete units");
assert.equal(pack(ordered, 0).length, 0);
const result = evaluateCase({candidates, gold_memory_ids: ["p1:t002", "p1:missing"]}, "logistic", 700);
assert.equal(result.annotatedRecall, 0.5, "Gold absent from the candidate pool stays in the denominator");
assert.equal(result.candidateRecall, 0.5);
assert.equal(result.tokenCount, 650);
assert.equal(result.ordered.length, 4, "Every candidate remains available");
assert.throws(() => ranked([candidates[0], candidates[0]], "logistic"), /Duplicate/);
assert.throws(() => ranked([row("bad", NaN, 2)], "logistic"), /Nonfinite/);
assert.throws(() => ranked(candidates, "gold"), /Unknown/);
assert.throws(() => pack([row("bad", 1, 1.5)], 2000), /Invalid token/);
assert.throws(() => pack(candidates, -1), /Budget/);
assert.throws(() => pack(candidates, 2000.5), /Budget/);
assert.throws(() => evaluateCase({candidates, gold_memory_ids: []}, "logistic", 700), /Annotated support/);
console.log("PASS: deterministic ties, no mutation, complete-unit packing, full candidate pool, missing-gold denominator, input validation.");
